#!/usr/bin/env python3
"""
Generate Swift file from country_details.json
Creates CountryDetailsData.generated.swift with static data.
"""

import json

JSON_FILE = "country_details.json"
SWIFT_FILE = "Tapaterra/Models/CountryDetailsData.generated.swift"

def swift_string_literal(value):
    """Convert a string to Swift string literal with proper escaping."""
    if value is None:
        return "nil"
    escaped = value.replace('\\', '\\\\').replace('"', '\\"').replace('\n', '\\n')
    return f'"{escaped}"'

def swift_array_literal(items):
    """Convert a list to Swift array literal."""
    if not items:
        return "[]"
    items_str = ", ".join([swift_string_literal(item) for item in items])
    return f"[{items_str}]"

def swift_optional_int(value):
    """Convert int to Swift optional Int."""
    if value is None:
        return "nil"
    return str(value)

def swift_optional_double(value):
    """Convert double to Swift optional Double."""
    if value is None:
        return "nil"
    return str(value)

def generate_swift_code(details_dict):
    """Generate Swift code from country details dictionary."""
    lines = []
    lines.append("import Foundation")
    lines.append("")
    lines.append("// Generated by script - do not edit manually")
    lines.append("// This file is auto-generated from country_details.json")
    lines.append("")
    lines.append("extension CountryDetailsData {")
    lines.append("    static func loadDetails() {")
    lines.append("        var detailsDict: [String: CountryDetails] = [:]")
    lines.append("")

    for iso_code, details in sorted(details_dict.items()):
        capital = swift_string_literal(details.get("capital"))
        cities = swift_array_literal(details.get("mainCities", []))
        rivers = swift_array_literal(details.get("mainRivers", []))
        mountains = swift_array_literal(details.get("mainMountains", []))
        neighbours = swift_array_literal(details.get("neighbours", []))
        population = swift_optional_int(details.get("population"))
        area = swift_optional_double(details.get("area"))
        currency = swift_string_literal(details.get("currency"))
        language = swift_string_literal(details.get("language"))

        lines.append(f'        detailsDict["{iso_code}"] = CountryDetails(')
        lines.append(f'            isoCode: "{iso_code}",')
        lines.append(f'            capital: {capital},')
        lines.append(f'            mainCities: {cities},')
        lines.append(f'            mainRivers: {rivers},')
        lines.append(f'            mainMountains: {mountains},')
        lines.append(f'            neighbours: {neighbours},')
        lines.append(f'            population: {population},')
        lines.append(f'            area: {area},')
        lines.append(f'            currency: {currency},')
        lines.append(f'            language: {language}')
        lines.append(f'        )')
        lines.append("")

    lines.append("        CountryDetailsData.details = detailsDict")
    lines.append("    }")
    lines.append("}")

    return "\n".join(lines)

def main():
    """Generate Swift file from JSON."""
    with open(JSON_FILE, "r", encoding="utf-8") as f:
        details_dict = json.load(f)

    swift_code = generate_swift_code(details_dict)

    with open(SWIFT_FILE, "w", encoding="utf-8") as f:
        f.write(swift_code)

    print(f"Generated {SWIFT_FILE} with {len(details_dict)} countries")

if __name__ == "__main__":
    main()

