import os

ASSETS_DIR = "Tapaterra/Assets.xcassets/Flags"
OUTPUT_FILE = "Tapaterra/FlagAssets.swift"

def to_camel_case(text):
    # algeria -> algeria
    # burkina-faso -> burkinaFaso
    components = text.split('-')
    return components[0] + ''.join(x.title() for x in components[1:])

def main():
    if not os.path.exists(ASSETS_DIR):
        print("Assets dir not found")
        return

    # Collect all flags
    # We'll organize them by region in the struct for nice access: Flags.Africa.algeria

    structure = {}

    for region in os.listdir(ASSETS_DIR):
        region_path = os.path.join(ASSETS_DIR, region)
        if not os.path.isdir(region_path) or region == "Contents.json":
            continue

        flags = []
        for item in os.listdir(region_path):
            if item.endswith(".imageset"):
                flag_name = item.replace(".imageset", "")
                flags.append(flag_name)

        if flags:
            structure[region] = sorted(flags)

    # Generate Swift Code
    lines = []
    lines.append("import SwiftUI")
    lines.append("")
    lines.append("// Generated by script - do not edit manually")
    lines.append("public struct FlagAssets {")

    sorted_regions = sorted(structure.keys())

    for region in sorted_regions:
        region_struct_name = region.replace(" ", "") # e.g. North_america -> NorthAmerica?
        # The folder names were capitalized by previous script: "Africa", "North_america"?
        # Let's check folder naming from previous step: `region.capitalize()`.
        # `north_america` -> `North_america`. Not ideal swift style.
        # Let's fix the Swift struct name to be PascalCase.

        clean_region_name = region.replace("_", " ").title().replace(" ", "")

        lines.append(f"    public struct {clean_region_name} {{")

        for flag in structure[region]:
            # flag is kebab-case: algeria or burkina-faso
            var_name = to_camel_case(flag)
            asset_name = f"Flags/{flag}"

            lines.append(f"        public static let {var_name} = Image(\"{asset_name}\")")
            lines.append(f"        public static let {var_name}Name = \"{asset_name}\"")

        lines.append("    }")
        lines.append("")

    # Also add a flat lookup if needed, or just rely on regions.
    # Regions are better for organization.

    lines.append("}")

    with open(OUTPUT_FILE, "w") as f:
        f.write("\n".join(lines))

    print(f"Generated {OUTPUT_FILE}")

if __name__ == "__main__":
    main()



