#!/usr/bin/env python3
"""
Generate ISO code mappings for countries.
This script creates a mapping from country names to ISO 3166-1 alpha-2 codes.
"""

# Common ISO code mappings - manually curated for the countries in FlagData.swift
ISO_MAPPING = {
    # Africa
    "Algeria": "DZ",
    "Angola": "AO",
    "Benin": "BJ",
    "Botswana": "BW",
    "Burkina Faso": "BF",
    "Burundi": "BI",
    "Cabo Verde": "CV",
    "Cameroon": "CM",
    "Central African Republic": "CF",
    "Chad": "TD",
    "Comoros": "KM",
    "Congo": "CG",
    "DR Congo": "CD",
    "Côte d'Ivoire": "CI",
    "Djibouti": "DJ",
    "Egypt": "EG",
    "Equatorial Guinea": "GQ",
    "Eritrea": "ER",
    "Eswatini": "SZ",
    "Ethiopia": "ET",
    "Gabon": "GA",
    "Gambia": "GM",
    "Ghana": "GH",
    "Guinea": "GN",
    "Guinea-Bissau": "GW",
    "Kenya": "KE",
    "Lesotho": "LS",
    "Liberia": "LR",
    "Libya": "LY",
    "Madagascar": "MG",
    "Malawi": "MW",
    "Mali": "ML",
    "Mauritania": "MR",
    "Mauritius": "MU",
    "Mayotte": "YT",
    "Morocco": "MA",
    "Mozambique": "MZ",
    "Namibia": "NA",
    "Niger": "NE",
    "Nigeria": "NG",
    "Réunion": "RE",
    "Rwanda": "RW",
    "Saint Helena": "SH",
    "São Tomé and Príncipe": "ST",
    "Senegal": "SN",
    "Seychelles": "SC",
    "Sierra Leone": "SL",
    "Somalia": "SO",
    "South Africa": "ZA",
    "South Sudan": "SS",
    "Sudan": "SD",
    "Tanzania": "TZ",
    "Togo": "TG",
    "Tunisia": "TN",
    "Uganda": "UG",
    "Western Sahara": "EH",
    "Zambia": "ZM",
    "Zimbabwe": "ZW",

    # Asia
    "Afghanistan": "AF",
    "Armenia": "AM",
    "Azerbaijan": "AZ",
    "Bahrain": "BH",
    "Bangladesh": "BD",
    "Bhutan": "BT",
    "Brunei": "BN",
    "Cambodia": "KH",
    "China": "CN",
    "Cyprus": "CY",
    "Georgia": "GE",
    "Hong Kong": "HK",
    "India": "IN",
    "Indonesia": "ID",
    "Iran": "IR",
    "Iraq": "IQ",
    "Israel": "IL",
    "Japan": "JP",
    "Jordan": "JO",
    "Kazakhstan": "KZ",
    "Kuwait": "KW",
    "Kyrgyzstan": "KG",
    "Laos": "LA",
    "Lebanon": "LB",
    "Macao": "MO",
    "Malaysia": "MY",
    "Maldives": "MV",
    "Mongolia": "MN",
    "Myanmar": "MM",
    "Nepal": "NP",
    "North Korea": "KP",
    "Oman": "OM",
    "Pakistan": "PK",
    "Palestine": "PS",
    "Philippines": "PH",
    "Qatar": "QA",
    "Saudi Arabia": "SA",
    "Singapore": "SG",
    "South Korea": "KR",
    "Sri Lanka": "LK",
    "Syria": "SY",
    "Taiwan": "TW",
    "Tajikistan": "TJ",
    "Thailand": "TH",
    "Timor-Leste": "TL",
    "Turkey": "TR",
    "Turkmenistan": "TM",
    "UAE": "AE",
    "Uzbekistan": "UZ",
    "Vietnam": "VN",
    "Yemen": "YE",

    # Europe
    "Åland Islands": "AX",
    "Albania": "AL",
    "Andorra": "AD",
    "Austria": "AT",
    "Belarus": "BY",
    "Belgium": "BE",
    "Bosnia and Herzegovina": "BA",
    "Bulgaria": "BG",
    "Croatia": "HR",
    "Czechia": "CZ",
    "Denmark": "DK",
    "Estonia": "EE",
    "Faroe Islands": "FO",
    "Finland": "FI",
    "France": "FR",
    "Germany": "DE",
    "Gibraltar": "GI",
    "Greece": "GR",
    "Guernsey": "GG",
    "Hungary": "HU",
    "Iceland": "IS",
    "Ireland": "IE",
    "Isle of Man": "IM",
    "Italy": "IT",
    "Jersey": "JE",
    "Kosovo": "XK",
    "Latvia": "LV",
    "Liechtenstein": "LI",
    "Lithuania": "LT",
    "Luxembourg": "LU",
    "Malta": "MT",
    "Moldova": "MD",
    "Monaco": "MC",
    "Montenegro": "ME",
    "Netherlands": "NL",
    "North Macedonia": "MK",
    "Norway": "NO",
    "Poland": "PL",
    "Portugal": "PT",
    "Romania": "RO",
    "Russia": "RU",
    "San Marino": "SM",
    "Serbia": "RS",
    "Slovakia": "SK",
    "Slovenia": "SI",
    "Spain": "ES",
    "Svalbard and Jan Mayen": "SJ",
    "Sweden": "SE",
    "Switzerland": "CH",
    "Ukraine": "UA",
    "United Kingdom": "GB",
    "Vatican City": "VA",

    # North America
    "Anguilla": "AI",
    "Antigua and Barbuda": "AG",
    "Aruba": "AW",
    "Bahamas": "BS",
    "Barbados": "BB",
    "Belize": "BZ",
    "Bermuda": "BM",
    "Bonaire": "BQ",
    "British Virgin Islands": "VG",
    "Canada": "CA",
    "Cayman Islands": "KY",
    "Costa Rica": "CR",
    "Cuba": "CU",
    "Curaçao": "CW",
    "Dominica": "DM",
    "Dominican Republic": "DO",
    "El Salvador": "SV",
    "Greenland": "GL",
    "Grenada": "GD",
    "Guadeloupe": "GP",
    "Guatemala": "GT",
    "Haiti": "HT",
    "Honduras": "HN",
    "Jamaica": "JM",
    "Martinique": "MQ",
    "Mexico": "MX",
    "Montserrat": "MS",
    "Nicaragua": "NI",
    "Panama": "PA",
    "Puerto Rico": "PR",
    "Saint Barthélemy": "BL",
    "Saint Kitts and Nevis": "KN",
    "Saint Lucia": "LC",
    "Saint Martin": "MF",
    "Saint Pierre and Miquelon": "PM",
    "Saint Vincent": "VC",
    "Sint Maarten": "SX",
    "Trinidad and Tobago": "TT",
    "Turks and Caicos": "TC",
    "United States": "US",
    "US Virgin Islands": "VI",

    # South America
    "Argentina": "AR",
    "Bolivia": "BO",
    "Brazil": "BR",
    "Chile": "CL",
    "Colombia": "CO",
    "Ecuador": "EC",
    "Falkland Islands": "FK",
    "French Guiana": "GF",
    "Guyana": "GY",
    "Paraguay": "PY",
    "Peru": "PE",
    "Suriname": "SR",
    "Uruguay": "UY",
    "Venezuela": "VE",

    # Oceania
    "American Samoa": "AS",
    "Australia": "AU",
    "Christmas Island": "CX",
    "Cocos Islands": "CC",
    "Cook Islands": "CK",
    "Fiji": "FJ",
    "French Polynesia": "PF",
    "Guam": "GU",
    "Kiribati": "KI",
    "Marshall Islands": "MH",
    "Micronesia": "FM",
    "Nauru": "NR",
    "New Caledonia": "NC",
    "New Zealand": "NZ",
    "Niue": "NU",
    "Norfolk Island": "NF",
    "Northern Mariana Islands": "MP",
    "Palau": "PW",
    "Papua New Guinea": "PG",
    "Pitcairn Islands": "PN",
    "Samoa": "WS",
    "Solomon Islands": "SB",
    "Tokelau": "TK",
    "Tonga": "TO",
    "Tuvalu": "TV",
    "Vanuatu": "VU",
    "Wallis and Futuna": "WF",

    # Antarctica
    "Antarctica": "AQ",
    "Bouvet Island": "BV",
    "French Southern Territories": "TF",
    "Heard Island": "HM",
    "South Georgia": "GS",
}

def get_iso_code(country_name: str) -> str:
    """Get ISO code for a country name."""
    return ISO_MAPPING.get(country_name, "XX")

if __name__ == "__main__":
    # Test
    print(f"Algeria -> {get_iso_code('Algeria')}")
    print(f"United States -> {get_iso_code('United States')}")

