import Foundation
import SwiftUI

enum Language: String, CaseIterable {
    case en, pl

    var displayName: String {
        switch self {
        case .en: return "English"
        case .pl: return "Polski"
        }
    }
}

@Observable
final class LanguageManager {
    static let shared = LanguageManager()

    var currentLanguage: Language {
        didSet {
            UserDefaults.standard.set(currentLanguage.rawValue, forKey: "appLanguage")
        }
    }

    private init() {
        let saved = UserDefaults.standard.string(forKey: "appLanguage")
        self.currentLanguage = Language(rawValue: saved ?? "") ?? .en
    }

    func setLanguage(_ lang: Language) {
        currentLanguage = lang
    }
}

// Static translations
enum L10n {
    static func get(_ key: String) -> String {
        let lang = LanguageManager.shared.currentLanguage
        return translations[lang]?[key] ?? key
    }

    // Translate currency name
    static func currency(_ englishName: String) -> String {
        let key = "currency.\(englishName)"
        let result = get(key)
        return result == key ? englishName : result
    }

    // Translate language name
    static func language(_ englishName: String) -> String {
        let key = "lang.\(englishName)"
        let result = get(key)
        return result == key ? englishName : result
    }

    // Translate neighbour country name (lookup by English name to ISO, then translate)
    static func neighbour(_ englishName: String) -> String {
        if let isoCode = countryNameToISO[englishName] {
            return get("country.\(isoCode)")
        }
        return englishName
    }

    // Translate capital city name
    static func capital(_ englishName: String) -> String {
        let key = "capital.\(englishName)"
        let result = get(key)
        return result == key ? englishName : result
    }

    // Lookup from English country name to ISO code
    private static let countryNameToISO: [String: String] = [
        "Afghanistan": "AF", "Albania": "AL", "Algeria": "DZ", "Andorra": "AD",
        "Angola": "AO", "Antigua and Barbuda": "AG", "Argentina": "AR", "Armenia": "AM",
        "Australia": "AU", "Austria": "AT", "Azerbaijan": "AZ", "Bahamas": "BS",
        "Bahrain": "BH", "Bangladesh": "BD", "Barbados": "BB", "Belarus": "BY",
        "Belgium": "BE", "Belize": "BZ", "Benin": "BJ", "Bhutan": "BT",
        "Bolivia": "BO", "Bosnia and Herzegovina": "BA", "Botswana": "BW", "Brazil": "BR",
        "Brunei": "BN", "Bulgaria": "BG", "Burkina Faso": "BF", "Burundi": "BI",
        "Cabo Verde": "CV", "Cambodia": "KH", "Cameroon": "CM", "Canada": "CA",
        "Central African Republic": "CF", "Chad": "TD", "Chile": "CL", "China": "CN",
        "Colombia": "CO", "Comoros": "KM", "Congo": "CG", "Costa Rica": "CR",
        "Croatia": "HR", "Cuba": "CU", "Cyprus": "CY", "Czechia": "CZ",
        "Denmark": "DK", "Djibouti": "DJ", "Dominica": "DM", "Dominican Republic": "DO",
        "DR Congo": "CD", "Ecuador": "EC", "Egypt": "EG", "El Salvador": "SV",
        "Equatorial Guinea": "GQ", "Eritrea": "ER", "Estonia": "EE", "Eswatini": "SZ",
        "Ethiopia": "ET", "Fiji": "FJ", "Finland": "FI", "France": "FR",
        "Gabon": "GA", "Gambia": "GM", "Georgia": "GE", "Germany": "DE",
        "Ghana": "GH", "Greece": "GR", "Grenada": "GD", "Guatemala": "GT",
        "Guinea": "GN", "Guinea-Bissau": "GW", "Guyana": "GY", "Haiti": "HT",
        "Honduras": "HN", "Hungary": "HU", "Iceland": "IS", "India": "IN",
        "Indonesia": "ID", "Iran": "IR", "Iraq": "IQ", "Ireland": "IE",
        "Israel": "IL", "Italy": "IT", "Jamaica": "JM", "Japan": "JP",
        "Jordan": "JO", "Kazakhstan": "KZ", "Kenya": "KE", "Kiribati": "KI",
        "Kosovo": "XK", "Kuwait": "KW", "Kyrgyzstan": "KG", "Laos": "LA",
        "Latvia": "LV", "Lebanon": "LB", "Lesotho": "LS", "Liberia": "LR",
        "Libya": "LY", "Liechtenstein": "LI", "Lithuania": "LT", "Luxembourg": "LU",
        "Madagascar": "MG", "Malawi": "MW", "Malaysia": "MY", "Maldives": "MV",
        "Mali": "ML", "Malta": "MT", "Marshall Islands": "MH", "Mauritania": "MR",
        "Mauritius": "MU", "Mexico": "MX", "Micronesia": "FM", "Moldova": "MD",
        "Monaco": "MC", "Mongolia": "MN", "Montenegro": "ME", "Morocco": "MA",
        "Mozambique": "MZ", "Myanmar": "MM", "Namibia": "NA", "Nauru": "NR",
        "Nepal": "NP", "Netherlands": "NL", "New Zealand": "NZ", "Nicaragua": "NI",
        "Niger": "NE", "Nigeria": "NG", "North Korea": "KP", "North Macedonia": "MK",
        "Norway": "NO", "Oman": "OM", "Pakistan": "PK", "Palau": "PW",
        "Palestine": "PS", "Panama": "PA", "Papua New Guinea": "PG", "Paraguay": "PY",
        "Peru": "PE", "Philippines": "PH", "Poland": "PL", "Portugal": "PT",
        "Qatar": "QA", "Romania": "RO", "Russia": "RU", "Rwanda": "RW",
        "Saint Kitts and Nevis": "KN", "Saint Lucia": "LC", "Saint Vincent and the Grenadines": "VC",
        "Samoa": "WS", "San Marino": "SM", "Saudi Arabia": "SA", "Senegal": "SN",
        "Serbia": "RS", "Seychelles": "SC", "Sierra Leone": "SL", "Singapore": "SG",
        "Slovakia": "SK", "Slovenia": "SI", "Solomon Islands": "SB", "Somalia": "SO",
        "South Africa": "ZA", "South Korea": "KR", "South Sudan": "SS", "Spain": "ES",
        "Sri Lanka": "LK", "Sudan": "SD", "Suriname": "SR", "Sweden": "SE",
        "Switzerland": "CH", "Syria": "SY", "Taiwan": "TW", "Tajikistan": "TJ",
        "Tanzania": "TZ", "Thailand": "TH", "Timor-Leste": "TL", "Togo": "TG",
        "Tonga": "TO", "Trinidad and Tobago": "TT", "Tunisia": "TN", "Turkey": "TR",
        "Turkmenistan": "TM", "Tuvalu": "TV", "Uganda": "UG", "Ukraine": "UA",
        "United Arab Emirates": "AE", "United Kingdom": "GB", "United States": "US",
        "Uruguay": "UY", "Uzbekistan": "UZ", "Vanuatu": "VU", "Vatican City": "VA",
        "Venezuela": "VE", "Vietnam": "VN", "Yemen": "YE", "Zambia": "ZM", "Zimbabwe": "ZW",
        "São Tomé and Príncipe": "ST", "Côte d'Ivoire": "CI", "Western Sahara": "EH",
    ]

    private static let translations: [Language: [String: String]] = [
        .en: enTranslations,
        .pl: plTranslations
    ]

    // MARK: - English Translations
    private static let enTranslations: [String: String] = [
        // Splash
        "splash.flags": "Flags",
        "splash.app_title": "Tapaterra",
        "splash.subtitle": "Explore the World's Flags",

        // Tabs
        "tab.learn": "Learn",
        "tab.play": "Play",
        "tab.settings": "Settings",

        // Continents
        "continent.all": "All",
        "continent.europe": "Europe",
        "continent.africa": "Africa",
        "continent.asia": "Asia",
        "continent.north_america": "North America",
        "continent.south_america": "South America",
        "continent.oceania": "Oceania",
        "continent.antarctica": "Antarctica",

        // Detail labels
        "detail.capital": "Capital",
        "detail.main_cities": "Main Cities",
        "detail.main_rivers": "Main Rivers",
        "detail.main_mountains": "Main Mountains",
        "detail.neighbours": "Neighbours",
        "detail.population": "Population",
        "detail.area": "Area",
        "detail.currency": "Currency",
        "detail.language": "Language",
        "detail.no_data": "No data available",
        "detail.scroll_hint": "Scroll for details",

        // Search
        "search.placeholder": "Search countries...",

        // Content View (legacy)
        "preview_flags": "Preview Flags",
        "add_item": "Add Item",
        "select_item": "Select an item",
        "item_at": "Item at",
        "language": "Language",
        "change_language": "Change Language",

        // Countries - Africa
        "country.DZ": "Algeria",
        "country.AO": "Angola",
        "country.BJ": "Benin",
        "country.BW": "Botswana",
        "country.BF": "Burkina Faso",
        "country.BI": "Burundi",
        "country.CV": "Cabo Verde",
        "country.CM": "Cameroon",
        "country.CF": "Central African Republic",
        "country.TD": "Chad",
        "country.KM": "Comoros",
        "country.CG": "Congo",
        "country.CD": "DR Congo",
        "country.CI": "Côte d'Ivoire",
        "country.DJ": "Djibouti",
        "country.EG": "Egypt",
        "country.GQ": "Equatorial Guinea",
        "country.ER": "Eritrea",
        "country.SZ": "Eswatini",
        "country.ET": "Ethiopia",
        "country.GA": "Gabon",
        "country.GM": "Gambia",
        "country.GH": "Ghana",
        "country.GN": "Guinea",
        "country.GW": "Guinea-Bissau",
        "country.KE": "Kenya",
        "country.LS": "Lesotho",
        "country.LR": "Liberia",
        "country.LY": "Libya",
        "country.MG": "Madagascar",
        "country.MW": "Malawi",
        "country.ML": "Mali",
        "country.MR": "Mauritania",
        "country.MU": "Mauritius",
        "country.YT": "Mayotte",
        "country.MA": "Morocco",
        "country.MZ": "Mozambique",
        "country.NA": "Namibia",
        "country.NE": "Niger",
        "country.NG": "Nigeria",
        "country.RE": "Réunion",
        "country.RW": "Rwanda",
        "country.SH": "Saint Helena",
        "country.ST": "São Tomé and Príncipe",
        "country.SN": "Senegal",
        "country.SC": "Seychelles",
        "country.SL": "Sierra Leone",
        "country.SO": "Somalia",
        "country.ZA": "South Africa",
        "country.SS": "South Sudan",
        "country.SD": "Sudan",
        "country.TZ": "Tanzania",
        "country.TG": "Togo",
        "country.TN": "Tunisia",
        "country.UG": "Uganda",
        "country.EH": "Western Sahara",
        "country.ZM": "Zambia",
        "country.ZW": "Zimbabwe",

        // Countries - Asia
        "country.AF": "Afghanistan",
        "country.AM": "Armenia",
        "country.AZ": "Azerbaijan",
        "country.BH": "Bahrain",
        "country.BD": "Bangladesh",
        "country.BT": "Bhutan",
        "country.BN": "Brunei",
        "country.KH": "Cambodia",
        "country.CN": "China",
        "country.CY": "Cyprus",
        "country.GE": "Georgia",
        "country.HK": "Hong Kong",
        "country.IN": "India",
        "country.ID": "Indonesia",
        "country.IR": "Iran",
        "country.IQ": "Iraq",
        "country.IL": "Israel",
        "country.JP": "Japan",
        "country.JO": "Jordan",
        "country.KZ": "Kazakhstan",
        "country.KW": "Kuwait",
        "country.KG": "Kyrgyzstan",
        "country.LA": "Laos",
        "country.LB": "Lebanon",
        "country.MO": "Macao",
        "country.MY": "Malaysia",
        "country.MV": "Maldives",
        "country.MN": "Mongolia",
        "country.MM": "Myanmar",
        "country.NP": "Nepal",
        "country.KP": "North Korea",
        "country.OM": "Oman",
        "country.PK": "Pakistan",
        "country.PS": "Palestine",
        "country.PH": "Philippines",
        "country.QA": "Qatar",
        "country.SA": "Saudi Arabia",
        "country.SG": "Singapore",
        "country.KR": "South Korea",
        "country.LK": "Sri Lanka",
        "country.SY": "Syria",
        "country.TW": "Taiwan",
        "country.TJ": "Tajikistan",
        "country.TH": "Thailand",
        "country.TL": "Timor-Leste",
        "country.TR": "Turkey",
        "country.TM": "Turkmenistan",
        "country.AE": "UAE",
        "country.UZ": "Uzbekistan",
        "country.VN": "Vietnam",
        "country.YE": "Yemen",

        // Countries - Europe
        "country.AX": "Åland Islands",
        "country.AL": "Albania",
        "country.AD": "Andorra",
        "country.AT": "Austria",
        "country.BY": "Belarus",
        "country.BE": "Belgium",
        "country.BA": "Bosnia and Herzegovina",
        "country.BG": "Bulgaria",
        "country.HR": "Croatia",
        "country.CZ": "Czechia",
        "country.DK": "Denmark",
        "country.EE": "Estonia",
        "country.FO": "Faroe Islands",
        "country.FI": "Finland",
        "country.FR": "France",
        "country.DE": "Germany",
        "country.GI": "Gibraltar",
        "country.GR": "Greece",
        "country.GG": "Guernsey",
        "country.HU": "Hungary",
        "country.IS": "Iceland",
        "country.IE": "Ireland",
        "country.IM": "Isle of Man",
        "country.IT": "Italy",
        "country.JE": "Jersey",
        "country.XK": "Kosovo",
        "country.LV": "Latvia",
        "country.LI": "Liechtenstein",
        "country.LT": "Lithuania",
        "country.LU": "Luxembourg",
        "country.MT": "Malta",
        "country.MD": "Moldova",
        "country.MC": "Monaco",
        "country.ME": "Montenegro",
        "country.NL": "Netherlands",
        "country.MK": "North Macedonia",
        "country.NO": "Norway",
        "country.PL": "Poland",
        "country.PT": "Portugal",
        "country.RO": "Romania",
        "country.RU": "Russia",
        "country.SM": "San Marino",
        "country.RS": "Serbia",
        "country.SK": "Slovakia",
        "country.SI": "Slovenia",
        "country.ES": "Spain",
        "country.SJ": "Svalbard and Jan Mayen",
        "country.SE": "Sweden",
        "country.CH": "Switzerland",
        "country.UA": "Ukraine",
        "country.GB": "United Kingdom",
        "country.VA": "Vatican City",

        // Countries - North America
        "country.AI": "Anguilla",
        "country.AG": "Antigua and Barbuda",
        "country.AW": "Aruba",
        "country.BS": "Bahamas",
        "country.BB": "Barbados",
        "country.BZ": "Belize",
        "country.BM": "Bermuda",
        "country.BQ": "Bonaire",
        "country.VG": "British Virgin Islands",
        "country.CA": "Canada",
        "country.KY": "Cayman Islands",
        "country.CR": "Costa Rica",
        "country.CU": "Cuba",
        "country.CW": "Curaçao",
        "country.DM": "Dominica",
        "country.DO": "Dominican Republic",
        "country.SV": "El Salvador",
        "country.GL": "Greenland",
        "country.GD": "Grenada",
        "country.GP": "Guadeloupe",
        "country.GT": "Guatemala",
        "country.HT": "Haiti",
        "country.HN": "Honduras",
        "country.JM": "Jamaica",
        "country.MQ": "Martinique",
        "country.MX": "Mexico",
        "country.MS": "Montserrat",
        "country.NI": "Nicaragua",
        "country.PA": "Panama",
        "country.PR": "Puerto Rico",
        "country.BL": "Saint Barthélemy",
        "country.KN": "Saint Kitts and Nevis",
        "country.LC": "Saint Lucia",
        "country.MF": "Saint Martin",
        "country.PM": "Saint Pierre and Miquelon",
        "country.VC": "Saint Vincent",
        "country.SX": "Sint Maarten",
        "country.TT": "Trinidad and Tobago",
        "country.TC": "Turks and Caicos",
        "country.US": "United States",
        "country.VI": "US Virgin Islands",

        // Countries - South America
        "country.AR": "Argentina",
        "country.BO": "Bolivia",
        "country.BR": "Brazil",
        "country.CL": "Chile",
        "country.CO": "Colombia",
        "country.EC": "Ecuador",
        "country.FK": "Falkland Islands",
        "country.GF": "French Guiana",
        "country.GY": "Guyana",
        "country.PY": "Paraguay",
        "country.PE": "Peru",
        "country.SR": "Suriname",
        "country.UY": "Uruguay",
        "country.VE": "Venezuela",

        // Countries - Oceania
        "country.AS": "American Samoa",
        "country.AU": "Australia",
        "country.CX": "Christmas Island",
        "country.CC": "Cocos Islands",
        "country.CK": "Cook Islands",
        "country.FJ": "Fiji",
        "country.PF": "French Polynesia",
        "country.GU": "Guam",
        "country.KI": "Kiribati",
        "country.MH": "Marshall Islands",
        "country.FM": "Micronesia",
        "country.NR": "Nauru",
        "country.NC": "New Caledonia",
        "country.NZ": "New Zealand",
        "country.NU": "Niue",
        "country.NF": "Norfolk Island",
        "country.MP": "Northern Mariana Islands",
        "country.PW": "Palau",
        "country.PG": "Papua New Guinea",
        "country.PN": "Pitcairn Islands",
        "country.WS": "Samoa",
        "country.SB": "Solomon Islands",
        "country.TK": "Tokelau",
        "country.TO": "Tonga",
        "country.TV": "Tuvalu",
        "country.VU": "Vanuatu",
        "country.WF": "Wallis and Futuna",

        // Countries - Antarctica
        "country.AQ": "Antarctica",
        "country.BV": "Bouvet Island",
        "country.TF": "French Southern Territories",
        "country.HM": "Heard Island",
        "country.GS": "South Georgia",
    ]

    // MARK: - Polish Translations
    private static let plTranslations: [String: String] = [
        // Splash
        "splash.flags": "Flagi",
        "splash.app_title": "Tapaterra",
        "splash.subtitle": "Poznaj flagi świata",

        // Tabs
        "tab.learn": "Nauka",
        "tab.play": "Gra",
        "tab.settings": "Ustawienia",

        // Continents
        "continent.all": "Wszystkie",
        "continent.europe": "Europa",
        "continent.africa": "Afryka",
        "continent.asia": "Azja",
        "continent.north_america": "Ameryka Północna",
        "continent.south_america": "Ameryka Południowa",
        "continent.oceania": "Oceania",
        "continent.antarctica": "Antarktyda",

        // Detail labels
        "detail.capital": "Stolica",
        "detail.main_cities": "Główne miasta",
        "detail.main_rivers": "Główne rzeki",
        "detail.main_mountains": "Główne góry",
        "detail.neighbours": "Sąsiedzi",
        "detail.population": "Populacja",
        "detail.area": "Powierzchnia",
        "detail.currency": "Waluta",
        "detail.language": "Język",
        "detail.no_data": "Brak danych",
        "detail.scroll_hint": "Przewiń, aby zobaczyć szczegóły",

        // Search
        "search.placeholder": "Szukaj krajów...",

        // Content View (legacy)
        "preview_flags": "Podgląd flag",
        "add_item": "Dodaj element",
        "select_item": "Wybierz element",
        "item_at": "Element z",
        "language": "Język",
        "change_language": "Zmień język",

        // Countries - Africa
        "country.DZ": "Algieria",
        "country.AO": "Angola",
        "country.BJ": "Benin",
        "country.BW": "Botswana",
        "country.BF": "Burkina Faso",
        "country.BI": "Burundi",
        "country.CV": "Republika Zielonego Przylądka",
        "country.CM": "Kamerun",
        "country.CF": "Republika Środkowoafrykańska",
        "country.TD": "Czad",
        "country.KM": "Komory",
        "country.CG": "Kongo",
        "country.CD": "Demokratyczna Republika Konga",
        "country.CI": "Wybrzeże Kości Słoniowej",
        "country.DJ": "Dżibuti",
        "country.EG": "Egipt",
        "country.GQ": "Gwinea Równikowa",
        "country.ER": "Erytrea",
        "country.SZ": "Eswatini",
        "country.ET": "Etiopia",
        "country.GA": "Gabon",
        "country.GM": "Gambia",
        "country.GH": "Ghana",
        "country.GN": "Gwinea",
        "country.GW": "Gwinea Bissau",
        "country.KE": "Kenia",
        "country.LS": "Lesotho",
        "country.LR": "Liberia",
        "country.LY": "Libia",
        "country.MG": "Madagaskar",
        "country.MW": "Malawi",
        "country.ML": "Mali",
        "country.MR": "Mauretania",
        "country.MU": "Mauritius",
        "country.YT": "Majotta",
        "country.MA": "Maroko",
        "country.MZ": "Mozambik",
        "country.NA": "Namibia",
        "country.NE": "Niger",
        "country.NG": "Nigeria",
        "country.RE": "Reunion",
        "country.RW": "Rwanda",
        "country.SH": "Wyspa Świętej Heleny",
        "country.ST": "Wyspy Świętego Tomasza i Książęca",
        "country.SN": "Senegal",
        "country.SC": "Seszele",
        "country.SL": "Sierra Leone",
        "country.SO": "Somalia",
        "country.ZA": "Republika Południowej Afryki",
        "country.SS": "Sudan Południowy",
        "country.SD": "Sudan",
        "country.TZ": "Tanzania",
        "country.TG": "Togo",
        "country.TN": "Tunezja",
        "country.UG": "Uganda",
        "country.EH": "Sahara Zachodnia",
        "country.ZM": "Zambia",
        "country.ZW": "Zimbabwe",

        // Countries - Asia
        "country.AF": "Afganistan",
        "country.AM": "Armenia",
        "country.AZ": "Azerbejdżan",
        "country.BH": "Bahrajn",
        "country.BD": "Bangladesz",
        "country.BT": "Bhutan",
        "country.BN": "Brunei",
        "country.KH": "Kambodża",
        "country.CN": "Chiny",
        "country.CY": "Cypr",
        "country.GE": "Gruzja",
        "country.HK": "Hongkong",
        "country.IN": "Indie",
        "country.ID": "Indonezja",
        "country.IR": "Iran",
        "country.IQ": "Irak",
        "country.IL": "Izrael",
        "country.JP": "Japonia",
        "country.JO": "Jordania",
        "country.KZ": "Kazachstan",
        "country.KW": "Kuwejt",
        "country.KG": "Kirgistan",
        "country.LA": "Laos",
        "country.LB": "Liban",
        "country.MO": "Makau",
        "country.MY": "Malezja",
        "country.MV": "Malediwy",
        "country.MN": "Mongolia",
        "country.MM": "Mjanma",
        "country.NP": "Nepal",
        "country.KP": "Korea Północna",
        "country.OM": "Oman",
        "country.PK": "Pakistan",
        "country.PS": "Palestyna",
        "country.PH": "Filipiny",
        "country.QA": "Katar",
        "country.SA": "Arabia Saudyjska",
        "country.SG": "Singapur",
        "country.KR": "Korea Południowa",
        "country.LK": "Sri Lanka",
        "country.SY": "Syria",
        "country.TW": "Tajwan",
        "country.TJ": "Tadżykistan",
        "country.TH": "Tajlandia",
        "country.TL": "Timor Wschodni",
        "country.TR": "Turcja",
        "country.TM": "Turkmenistan",
        "country.AE": "Zjednoczone Emiraty Arabskie",
        "country.UZ": "Uzbekistan",
        "country.VN": "Wietnam",
        "country.YE": "Jemen",

        // Countries - Europe
        "country.AX": "Wyspy Alandzkie",
        "country.AL": "Albania",
        "country.AD": "Andora",
        "country.AT": "Austria",
        "country.BY": "Białoruś",
        "country.BE": "Belgia",
        "country.BA": "Bośnia i Hercegowina",
        "country.BG": "Bułgaria",
        "country.HR": "Chorwacja",
        "country.CZ": "Czechy",
        "country.DK": "Dania",
        "country.EE": "Estonia",
        "country.FO": "Wyspy Owcze",
        "country.FI": "Finlandia",
        "country.FR": "Francja",
        "country.DE": "Niemcy",
        "country.GI": "Gibraltar",
        "country.GR": "Grecja",
        "country.GG": "Guernsey",
        "country.HU": "Węgry",
        "country.IS": "Islandia",
        "country.IE": "Irlandia",
        "country.IM": "Wyspa Man",
        "country.IT": "Włochy",
        "country.JE": "Jersey",
        "country.XK": "Kosowo",
        "country.LV": "Łotwa",
        "country.LI": "Liechtenstein",
        "country.LT": "Litwa",
        "country.LU": "Luksemburg",
        "country.MT": "Malta",
        "country.MD": "Mołdawia",
        "country.MC": "Monako",
        "country.ME": "Czarnogóra",
        "country.NL": "Holandia",
        "country.MK": "Macedonia Północna",
        "country.NO": "Norwegia",
        "country.PL": "Polska",
        "country.PT": "Portugalia",
        "country.RO": "Rumunia",
        "country.RU": "Rosja",
        "country.SM": "San Marino",
        "country.RS": "Serbia",
        "country.SK": "Słowacja",
        "country.SI": "Słowenia",
        "country.ES": "Hiszpania",
        "country.SJ": "Svalbard i Jan Mayen",
        "country.SE": "Szwecja",
        "country.CH": "Szwajcaria",
        "country.UA": "Ukraina",
        "country.GB": "Wielka Brytania",
        "country.VA": "Watykan",

        // Countries - North America
        "country.AI": "Anguilla",
        "country.AG": "Antigua i Barbuda",
        "country.AW": "Aruba",
        "country.BS": "Bahamy",
        "country.BB": "Barbados",
        "country.BZ": "Belize",
        "country.BM": "Bermudy",
        "country.BQ": "Bonaire",
        "country.VG": "Brytyjskie Wyspy Dziewicze",
        "country.CA": "Kanada",
        "country.KY": "Kajmany",
        "country.CR": "Kostaryka",
        "country.CU": "Kuba",
        "country.CW": "Curaçao",
        "country.DM": "Dominika",
        "country.DO": "Dominikana",
        "country.SV": "Salwador",
        "country.GL": "Grenlandia",
        "country.GD": "Grenada",
        "country.GP": "Gwadelupa",
        "country.GT": "Gwatemala",
        "country.HT": "Haiti",
        "country.HN": "Honduras",
        "country.JM": "Jamajka",
        "country.MQ": "Martynika",
        "country.MX": "Meksyk",
        "country.MS": "Montserrat",
        "country.NI": "Nikaragua",
        "country.PA": "Panama",
        "country.PR": "Portoryko",
        "country.BL": "Saint-Barthélemy",
        "country.KN": "Saint Kitts i Nevis",
        "country.LC": "Saint Lucia",
        "country.MF": "Saint-Martin",
        "country.PM": "Saint-Pierre i Miquelon",
        "country.VC": "Saint Vincent i Grenadyny",
        "country.SX": "Sint Maarten",
        "country.TT": "Trynidad i Tobago",
        "country.TC": "Turks i Caicos",
        "country.US": "Stany Zjednoczone",
        "country.VI": "Wyspy Dziewicze Stanów Zjednoczonych",

        // Countries - South America
        "country.AR": "Argentyna",
        "country.BO": "Boliwia",
        "country.BR": "Brazylia",
        "country.CL": "Chile",
        "country.CO": "Kolumbia",
        "country.EC": "Ekwador",
        "country.FK": "Falklandy",
        "country.GF": "Gujana Francuska",
        "country.GY": "Gujana",
        "country.PY": "Paragwaj",
        "country.PE": "Peru",
        "country.SR": "Surinam",
        "country.UY": "Urugwaj",
        "country.VE": "Wenezuela",

        // Countries - Oceania
        "country.AS": "Samoa Amerykańskie",
        "country.AU": "Australia",
        "country.CX": "Wyspa Bożego Narodzenia",
        "country.CC": "Wyspy Kokosowe",
        "country.CK": "Wyspy Cooka",
        "country.FJ": "Fidżi",
        "country.PF": "Polinezja Francuska",
        "country.GU": "Guam",
        "country.KI": "Kiribati",
        "country.MH": "Wyspy Marshalla",
        "country.FM": "Mikronezja",
        "country.NR": "Nauru",
        "country.NC": "Nowa Kaledonia",
        "country.NZ": "Nowa Zelandia",
        "country.NU": "Niue",
        "country.NF": "Norfolk",
        "country.MP": "Mariany Północne",
        "country.PW": "Palau",
        "country.PG": "Papua-Nowa Gwinea",
        "country.PN": "Pitcairn",
        "country.WS": "Samoa",
        "country.SB": "Wyspy Salomona",
        "country.TK": "Tokelau",
        "country.TO": "Tonga",
        "country.TV": "Tuvalu",
        "country.VU": "Vanuatu",
        "country.WF": "Wallis i Futuna",

        // Countries - Antarctica
        "country.AQ": "Antarktyda",
        "country.BV": "Wyspa Bouveta",
        "country.TF": "Francuskie Terytoria Południowe",
        "country.HM": "Wyspa Heard i Wyspy McDonalda",
        "country.GS": "Georgia Południowa",

        // Currencies
        "currency.Euro": "Euro",
        "currency.United Arab Emirates dirham": "Dirham ZEA",
        "currency.Afghan afghani": "Afgani afgański",
        "currency.Eastern Caribbean dollar": "Dolar wschodniokaraibski",
        "currency.Albanian lek": "Lek albański",
        "currency.Armenian dram": "Dram armeński",
        "currency.Netherlands Antillean guilder": "Gulden antylski",
        "currency.Angolan kwanza": "Kwanza angolska",
        "currency.Argentine peso": "Peso argentyńskie",
        "currency.Australian dollar": "Dolar australijski",
        "currency.Aruban florin": "Florin arubański",
        "currency.Azerbaijani manat": "Manat azerbejdżański",
        "currency.Bosnia and Herzegovina convertible mark": "Marka zamienna Bośni i Hercegowiny",
        "currency.Barbadian dollar": "Dolar barbadoski",
        "currency.Bangladeshi taka": "Taka bengalska",
        "currency.Bulgarian lev": "Lew bułgarski",
        "currency.Bahraini dinar": "Dinar bahrajński",
        "currency.Burundian franc": "Frank burundyjski",
        "currency.West African CFA franc": "Frank CFA",
        "currency.Bermudian dollar": "Dolar bermudzki",
        "currency.Brunei dollar": "Dolar brunejski",
        "currency.Bolivian boliviano": "Boliwiano boliwijskie",
        "currency.Brazilian real": "Real brazylijski",
        "currency.Bahamian dollar": "Dolar bahamski",
        "currency.Bhutanese ngultrum": "Ngultrum bhutański",
        "currency.Botswana pula": "Pula botswańska",
        "currency.Belarusian ruble": "Rubel białoruski",
        "currency.Belize dollar": "Dolar belizeński",
        "currency.Canadian dollar": "Dolar kanadyjski",
        "currency.Congolese franc": "Frank kongijski",
        "currency.Swiss franc": "Frank szwajcarski",
        "currency.Chilean peso": "Peso chilijskie",
        "currency.Chinese yuan": "Juan chiński",
        "currency.Colombian peso": "Peso kolumbijskie",
        "currency.Costa Rican colón": "Kolon kostarykański",
        "currency.Cuban peso": "Peso kubańskie",
        "currency.Cape Verdean escudo": "Escudo Zielonego Przylądka",
        "currency.Czech koruna": "Korona czeska",
        "currency.Djiboutian franc": "Frank dżibutyjski",
        "currency.Danish krone": "Korona duńska",
        "currency.Dominican peso": "Peso dominikańskie",
        "currency.Algerian dinar": "Dinar algierski",
        "currency.Egyptian pound": "Funt egipski",
        "currency.Eritrean nakfa": "Nakfa erytrejska",
        "currency.Ethiopian birr": "Birr etiopski",
        "currency.Fijian dollar": "Dolar fidżijski",
        "currency.Falkland Islands pound": "Funt falklandzki",
        "currency.Pound sterling": "Funt szterling",
        "currency.Georgian lari": "Lari gruzińskie",
        "currency.Ghanaian cedi": "Cedi ghański",
        "currency.Gibraltar pound": "Funt gibraltarski",
        "currency.Gambian dalasi": "Dalasi gambijski",
        "currency.Guinean franc": "Frank gwinejski",
        "currency.Guatemalan quetzal": "Quetzal gwatemalski",
        "currency.Guyanese dollar": "Dolar gujański",
        "currency.Hong Kong dollar": "Dolar hongkoński",
        "currency.Honduran lempira": "Lempira honduraska",
        "currency.Croatian kuna": "Kuna chorwacka",
        "currency.Haitian gourde": "Gourde haitańska",
        "currency.Hungarian forint": "Forint węgierski",
        "currency.Indonesian rupiah": "Rupia indonezyjska",
        "currency.Israeli new shekel": "Nowy szekel izraelski",
        "currency.Indian rupee": "Rupia indyjska",
        "currency.Iraqi dinar": "Dinar iracki",
        "currency.Iranian rial": "Rial irański",
        "currency.Icelandic króna": "Korona islandzka",
        "currency.Jamaican dollar": "Dolar jamajski",
        "currency.Jordanian dinar": "Dinar jordański",
        "currency.Japanese yen": "Jen japoński",
        "currency.Kenyan shilling": "Szyling kenijski",
        "currency.Kyrgyzstani som": "Som kirgiski",
        "currency.Cambodian riel": "Riel kambodżański",
        "currency.Comorian franc": "Frank komoryjski",
        "currency.North Korean won": "Won północnokoreański",
        "currency.South Korean won": "Won południowokoreański",
        "currency.Kuwaiti dinar": "Dinar kuwejcki",
        "currency.Cayman Islands dollar": "Dolar kajmański",
        "currency.Kazakhstani tenge": "Tenge kazachskie",
        "currency.Lao kip": "Kip laotański",
        "currency.Lebanese pound": "Funt libański",
        "currency.Sri Lankan rupee": "Rupia lankijska",
        "currency.Liberian dollar": "Dolar liberyjski",
        "currency.Lesotho loti": "Loti Lesotho",
        "currency.Libyan dinar": "Dinar libijski",
        "currency.Moroccan dirham": "Dirham marokański",
        "currency.Moldovan leu": "Lej mołdawski",
        "currency.Malagasy ariary": "Ariary malgaski",
        "currency.Macedonian denar": "Denar macedoński",
        "currency.Myanmar kyat": "Kiat birmański",
        "currency.Mongolian tögrög": "Tugrik mongolski",
        "currency.Macanese pataca": "Pataca Makau",
        "currency.Mauritanian ouguiya": "Ugija mauretańska",
        "currency.Mauritian rupee": "Rupia maurytyjska",
        "currency.Maldivian rufiyaa": "Rupia malediwska",
        "currency.Malawian kwacha": "Kwacha malawijska",
        "currency.Mexican peso": "Peso meksykańskie",
        "currency.Malaysian ringgit": "Ringgit malezyjski",
        "currency.Mozambican metical": "Metical mozambicki",
        "currency.Namibian dollar": "Dolar namibijski",
        "currency.CFP franc": "Frank CFP",
        "currency.Nigerian naira": "Naira nigeryjska",
        "currency.Nicaraguan córdoba": "Kordoba nikaragwańska",
        "currency.Norwegian krone": "Korona norweska",
        "currency.Nepalese rupee": "Rupia nepalska",
        "currency.New Zealand dollar": "Dolar nowozelandzki",
        "currency.Omani rial": "Rial omański",
        "currency.Panamanian balboa": "Balboa panamska",
        "currency.Peruvian sol": "Sol peruwiański",
        "currency.Papua New Guinean kina": "Kina Papua-Nowej Gwinei",
        "currency.Philippine peso": "Peso filipińskie",
        "currency.Pakistani rupee": "Rupia pakistańska",
        "currency.Polish złoty": "Złoty polski",
        "currency.Paraguayan guaraní": "Guarani paragwajskie",
        "currency.Qatari riyal": "Rial katarski",
        "currency.Romanian leu": "Lej rumuński",
        "currency.Serbian dinar": "Dinar serbski",
        "currency.Russian ruble": "Rubel rosyjski",
        "currency.Rwandan franc": "Frank rwandyjski",
        "currency.Saudi riyal": "Rial saudyjski",
        "currency.Solomon Islands dollar": "Dolar Wysp Salomona",
        "currency.Seychellois rupee": "Rupia seszelska",
        "currency.Sudanese pound": "Funt sudański",
        "currency.Swedish krona": "Korona szwedzka",
        "currency.Singapore dollar": "Dolar singapurski",
        "currency.Saint Helena pound": "Funt Świętej Heleny",
        "currency.Sierra Leonean leone": "Leone sierraleoński",
        "currency.Somali shilling": "Szyling somalijski",
        "currency.Surinamese dollar": "Dolar surinamski",
        "currency.South Sudanese pound": "Funt południowosudański",
        "currency.São Tomé and Príncipe dobra": "Dobra Wysp Świętego Tomasza",
        "currency.Syrian pound": "Funt syryjski",
        "currency.Swazi lilangeni": "Lilangeni Eswatini",
        "currency.Thai baht": "Bat tajski",
        "currency.Tajikistani somoni": "Somoni tadżyckie",
        "currency.Turkmenistani manat": "Manat turkmeński",
        "currency.Tunisian dinar": "Dinar tunezyjski",
        "currency.Tongan paʻanga": "Pa'anga tongijskie",
        "currency.Turkish lira": "Lira turecka",
        "currency.Trinidad and Tobago dollar": "Dolar Trynidadu i Tobago",
        "currency.New Taiwan dollar": "Nowy dolar tajwański",
        "currency.Tanzanian shilling": "Szyling tanzański",
        "currency.Ukrainian hryvnia": "Hrywna ukraińska",
        "currency.Ugandan shilling": "Szyling ugandyjski",
        "currency.United States dollar": "Dolar amerykański",
        "currency.Uruguayan peso": "Peso urugwajskie",
        "currency.Uzbekistani soʻm": "Sum uzbecki",
        "currency.Venezuelan bolívar": "Boliwar wenezuelski",
        "currency.Vietnamese đồng": "Dong wietnamski",
        "currency.Vanuatu vatu": "Vatu Vanuatu",
        "currency.Samoan tālā": "Tala samoańska",
        "currency.Central African CFA franc": "Frank CFA Afryki Środkowej",
        "currency.Yemeni rial": "Rial jemeński",
        "currency.South African rand": "Rand południowoafrykański",
        "currency.Zambian kwacha": "Kwacha zambijska",

        // Languages
        "lang.Catalan": "Kataloński",
        "lang.Arabic": "Arabski",
        "lang.Dari": "Dari",
        "lang.English": "Angielski",
        "lang.Albanian": "Albański",
        "lang.Armenian": "Ormiański",
        "lang.Dutch": "Niderlandzki",
        "lang.Spanish": "Hiszpański",
        "lang.Portuguese": "Portugalski",
        "lang.Azerbaijani": "Azerski",
        "lang.Bosnian": "Bośniacki",
        "lang.Bengali": "Bengalski",
        "lang.Bulgarian": "Bułgarski",
        "lang.French": "Francuski",
        "lang.Rundi": "Rundi",
        "lang.Malay": "Malajski",
        "lang.Dzongkha": "Dzongkha",
        "lang.Setswana": "Setswana",
        "lang.Belarusian": "Białoruski",
        "lang.Lingala": "Lingala",
        "lang.German": "Niemiecki",
        "lang.Mandarin Chinese": "Chiński mandaryński",
        "lang.Comorian": "Komoryjski",
        "lang.Czech": "Czeski",
        "lang.Danish": "Duński",
        "lang.Somali": "Somalijski",
        "lang.Greek": "Grecki",
        "lang.Tigrinya": "Tigrinia",
        "lang.Swazi": "Swazi",
        "lang.Amharic": "Amharski",
        "lang.Fijian": "Fidżyjski",
        "lang.Finnish": "Fiński",
        "lang.Estonian": "Estoński",
        "lang.Faroese": "Farerski",
        "lang.Georgian": "Gruziński",
        "lang.Cantonese": "Kantoński",
        "lang.Hindi": "Hindi",
        "lang.Indonesian": "Indonezyjski",
        "lang.Persian": "Perski",
        "lang.Hebrew": "Hebrajski",
        "lang.Italian": "Włoski",
        "lang.Japanese": "Japoński",
        "lang.Kazakh": "Kazachski",
        "lang.Swahili": "Suahili",
        "lang.Kyrgyz": "Kirgiski",
        "lang.Lao": "Laotański",
        "lang.Latvian": "Łotewski",
        "lang.Sinhala": "Syngaleski",
        "lang.Sotho": "Sotho",
        "lang.Lithuanian": "Litewski",
        "lang.Luxembourgish": "Luksemburski",
        "lang.Malagasy": "Malgaski",
        "lang.Chichewa": "Chichewa",
        "lang.Macedonian": "Macedoński",
        "lang.Bambara": "Bambara",
        "lang.Maltese": "Maltański",
        "lang.Marshallese": "Marszalski",
        "lang.Romanian": "Rumuński",
        "lang.Mongolian": "Mongolski",
        "lang.Burmese": "Birmański",
        "lang.Nepali": "Nepalski",
        "lang.Korean": "Koreański",
        "lang.Norwegian": "Norweski",
        "lang.Hausa": "Hausa",
        "lang.Palauan": "Palauański",
        "lang.Tok Pisin": "Tok pisin",
        "lang.Filipino": "Filipiński",
        "lang.Urdu": "Urdu",
        "lang.Polish": "Polski",
        "lang.Guarani": "Guarani",
        "lang.Russian": "Rosyjski",
        "lang.Kinyarwanda": "Kinyarwanda",
        "lang.Samoan": "Samoański",
        "lang.Serbian": "Serbski",
        "lang.Seychellois Creole": "Kreolski seszelski",
        "lang.Krio": "Krio",
        "lang.Slovak": "Słowacki",
        "lang.Slovene": "Słoweński",
        "lang.Afrikaans": "Afrykanerski",
        "lang.Tamil": "Tamilski",
        "lang.Divehi": "Malediwski",
        "lang.Swedish": "Szwedzki",
        "lang.Tetum": "Tetum",
        "lang.Thai": "Tajski",
        "lang.Tajik": "Tadżycki",
        "lang.Ewe": "Ewe",
        "lang.Tongan": "Tongijski",
        "lang.Turkish": "Turecki",
        "lang.Turkmen": "Turkmeński",
        "lang.Tuvaluan": "Tuwalski",
        "lang.Ukrainian": "Ukraiński",
        "lang.Uzbek": "Uzbecki",
        "lang.Bislama": "Bislama",
        "lang.Vietnamese": "Wietnamski",
        "lang.Hungarian": "Węgierski",
        "lang.Icelandic": "Islandzki",
        "lang.Irish": "Irlandzki",
        "lang.Hassaniya Arabic": "Arabski hasanija",
        "lang.Shona": "Shona",
        "lang.Zulu": "Zulu",
        "lang.Croatian": "Chorwacki",
        "lang.Haitian Creole": "Kreolski haitański",
        "lang.Khmer": "Khmerski",

        // Capital cities (Polish versions)
        "capital.Vienna": "Wiedeń",
        "capital.Brussels": "Bruksela",
        "capital.Sofia": "Sofia",
        "capital.Zagreb": "Zagrzeb",
        "capital.Prague": "Praga",
        "capital.Copenhagen": "Kopenhaga",
        "capital.Tallinn": "Tallin",
        "capital.Helsinki": "Helsinki",
        "capital.Paris": "Paryż",
        "capital.Berlin": "Berlin",
        "capital.Athens": "Ateny",
        "capital.Budapest": "Budapeszt",
        "capital.Reykjavik": "Rejkiawik",
        "capital.Dublin": "Dublin",
        "capital.Rome": "Rzym",
        "capital.Riga": "Ryga",
        "capital.Vilnius": "Wilno",
        "capital.Luxembourg": "Luksemburg",
        "capital.Valletta": "Valletta",
        "capital.Amsterdam": "Amsterdam",
        "capital.Oslo": "Oslo",
        "capital.Warsaw": "Warszawa",
        "capital.Lisbon": "Lizbona",
        "capital.Bucharest": "Bukareszt",
        "capital.Moscow": "Moskwa",
        "capital.Belgrade": "Belgrad",
        "capital.Bratislava": "Bratysława",
        "capital.Ljubljana": "Lublana",
        "capital.Madrid": "Madryt",
        "capital.Stockholm": "Sztokholm",
        "capital.Bern": "Berno",
        "capital.Kyiv": "Kijów",
        "capital.London": "Londyn",
        "capital.Tirana": "Tirana",
        "capital.Minsk": "Mińsk",
        "capital.Sarajevo": "Sarajewo",
        "capital.Skopje": "Skopje",
        "capital.Podgorica": "Podgorica",
        "capital.Chisinau": "Kiszyniów",
        "capital.Vaduz": "Vaduz",
        "capital.Monaco": "Monako",
        "capital.San Marino": "San Marino",
        "capital.Vatican City": "Watykan",
        "capital.Andorra la Vella": "Andora la Vella",
        // Asia
        "capital.Kabul": "Kabul",
        "capital.Yerevan": "Erywań",
        "capital.Baku": "Baku",
        "capital.Manama": "Manama",
        "capital.Dhaka": "Dhaka",
        "capital.Thimphu": "Thimphu",
        "capital.Bandar Seri Begawan": "Bandar Seri Begawan",
        "capital.Phnom Penh": "Phnom Penh",
        "capital.Beijing": "Pekin",
        "capital.Nicosia": "Nikozja",
        "capital.Tbilisi": "Tbilisi",
        "capital.New Delhi": "Nowe Delhi",
        "capital.Jakarta": "Dżakarta",
        "capital.Tehran": "Teheran",
        "capital.Baghdad": "Bagdad",
        "capital.Jerusalem": "Jerozolima",
        "capital.Tokyo": "Tokio",
        "capital.Amman": "Amman",
        "capital.Astana": "Astana",
        "capital.Kuwait City": "Kuwejt",
        "capital.Bishkek": "Biszkek",
        "capital.Vientiane": "Wientian",
        "capital.Beirut": "Bejrut",
        "capital.Kuala Lumpur": "Kuala Lumpur",
        "capital.Malé": "Malé",
        "capital.Ulaanbaatar": "Ułan Bator",
        "capital.Naypyidaw": "Naypyidaw",
        "capital.Kathmandu": "Katmandu",
        "capital.Pyongyang": "Pjongjang",
        "capital.Muscat": "Maskat",
        "capital.Islamabad": "Islamabad",
        "capital.Manila": "Manila",
        "capital.Doha": "Doha",
        "capital.Riyadh": "Rijad",
        "capital.Singapore": "Singapur",
        "capital.Seoul": "Seul",
        "capital.Colombo": "Kolombo",
        "capital.Damascus": "Damaszek",
        "capital.Taipei": "Tajpej",
        "capital.Dushanbe": "Duszanbe",
        "capital.Bangkok": "Bangkok",
        "capital.Dili": "Dili",
        "capital.Ankara": "Ankara",
        "capital.Ashgabat": "Aszchabad",
        "capital.Abu Dhabi": "Abu Zabi",
        "capital.Tashkent": "Taszkent",
        "capital.Hanoi": "Hanoi",
        "capital.Sanaa": "Sana",
        // Africa
        "capital.Algiers": "Algier",
        "capital.Luanda": "Luanda",
        "capital.Gaborone": "Gaborone",
        "capital.Ouagadougou": "Wagadugu",
        "capital.Bujumbura": "Bużumbura",
        "capital.Praia": "Praia",
        "capital.Yaoundé": "Jaunde",
        "capital.Bangui": "Bangi",
        "capital.N'Djamena": "Ndżamena",
        "capital.Moroni": "Moroni",
        "capital.Brazzaville": "Brazzaville",
        "capital.Kinshasa": "Kinszasa",
        "capital.Yamoussoukro": "Jamusukro",
        "capital.Djibouti": "Dżibuti",
        "capital.Cairo": "Kair",
        "capital.Malabo": "Malabo",
        "capital.Asmara": "Asmara",
        "capital.Mbabane": "Mbabane",
        "capital.Addis Ababa": "Addis Abeba",
        "capital.Libreville": "Libreville",
        "capital.Banjul": "Bandżul",
        "capital.Accra": "Akra",
        "capital.Conakry": "Konakry",
        "capital.Bissau": "Bissau",
        "capital.Nairobi": "Nairobi",
        "capital.Maseru": "Maseru",
        "capital.Monrovia": "Monrowia",
        "capital.Tripoli": "Trypolis",
        "capital.Antananarivo": "Antananarywa",
        "capital.Lilongwe": "Lilongwe",
        "capital.Bamako": "Bamako",
        "capital.Nouakchott": "Nawakszut",
        "capital.Port Louis": "Port Louis",
        "capital.Rabat": "Rabat",
        "capital.Maputo": "Maputo",
        "capital.Windhoek": "Windhuk",
        "capital.Niamey": "Niamey",
        "capital.Abuja": "Abudża",
        "capital.Kigali": "Kigali",
        "capital.São Tomé": "São Tomé",
        "capital.Dakar": "Dakar",
        "capital.Victoria": "Victoria",
        "capital.Freetown": "Freetown",
        "capital.Mogadishu": "Mogadiszu",
        "capital.Pretoria": "Pretoria",
        "capital.Juba": "Dżuba",
        "capital.Khartoum": "Chartum",
        "capital.Dodoma": "Dodoma",
        "capital.Lomé": "Lomé",
        "capital.Tunis": "Tunis",
        "capital.Kampala": "Kampala",
        "capital.Lusaka": "Lusaka",
        "capital.Harare": "Harare",
        // Americas
        "capital.Buenos Aires": "Buenos Aires",
        "capital.La Paz": "La Paz",
        "capital.Brasília": "Brasília",
        "capital.Santiago": "Santiago",
        "capital.Bogotá": "Bogota",
        "capital.Quito": "Quito",
        "capital.Georgetown": "Georgetown",
        "capital.Asunción": "Asunción",
        "capital.Lima": "Lima",
        "capital.Paramaribo": "Paramaribo",
        "capital.Montevideo": "Montevideo",
        "capital.Caracas": "Caracas",
        "capital.Ottawa": "Ottawa",
        "capital.Washington, D.C.": "Waszyngton",
        "capital.Mexico City": "Meksyk",
        "capital.Guatemala City": "Gwatemala",
        "capital.Tegucigalpa": "Tegucigalpa",
        "capital.San Salvador": "San Salvador",
        "capital.Managua": "Managua",
        "capital.San José": "San José",
        "capital.Panama City": "Panama",
        "capital.Havana": "Hawana",
        "capital.Kingston": "Kingston",
        "capital.Port-au-Prince": "Port-au-Prince",
        "capital.Santo Domingo": "Santo Domingo",
        // Oceania
        "capital.Canberra": "Canberra",
        "capital.Suva": "Suva",
        "capital.Tarawa": "Tarawa",
        "capital.Majuro": "Majuro",
        "capital.Palikir": "Palikir",
        "capital.Yaren": "Yaren",
        "capital.Wellington": "Wellington",
        "capital.Ngerulmud": "Ngerulmud",
        "capital.Port Moresby": "Port Moresby",
        "capital.Apia": "Apia",
        "capital.Honiara": "Honiara",
        "capital.Nukuʻalofa": "Nuku'alofa",
        "capital.Funafuti": "Funafuti",
        "capital.Port Vila": "Port Vila",
    ]
}
